"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authCheck_1 = require("../../utils/authCheck");
const channels_1 = require("../../controllers/lnd/channels");
const router = express_1.Router();
router.get('/', authCheck_1.isAuthenticated, channels_1.getAllChannels);
router.get('/pending', authCheck_1.isAuthenticated, channels_1.getPendingChannels);
router.get('/closed', authCheck_1.isAuthenticated, channels_1.getClosedChannels);
router.post('/', authCheck_1.isAuthenticated, channels_1.postChannel);
router.post('/transactions', authCheck_1.isAuthenticated, channels_1.postTransactions);
router.delete('/:channelPoint', authCheck_1.isAuthenticated, channels_1.closeChannel);
router.post('/chanPolicy', authCheck_1.isAuthenticated, channels_1.postChanPolicy);
exports.default = router;
