"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authCheck_1 = require("../../utils/authCheck");
const channels_1 = require("../../controllers/eclair/channels");
const router = express_1.Router();
router.get('/', authCheck_1.isAuthenticated, channels_1.getChannels);
router.get('/stats', authCheck_1.isAuthenticated, channels_1.getChannelStats);
router.post('/', authCheck_1.isAuthenticated, channels_1.openChannel);
router.post('/updateRelayFee', authCheck_1.isAuthenticated, channels_1.updateChannelRelayFee);
router.delete('/', authCheck_1.isAuthenticated, channels_1.closeChannel);
exports.default = router;
