"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authCheck_1 = require("../../utils/authCheck");
const channels_1 = require("../../controllers/c-lightning/channels");
const router = express_1.Router();
router.get('/listChannels', authCheck_1.isAuthenticated, channels_1.listChannels);
router.post('/', authCheck_1.isAuthenticated, channels_1.openChannel);
router.post('/setChannelFee', authCheck_1.isAuthenticated, channels_1.setChannelFee);
router.delete('/:channelId', authCheck_1.isAuthenticated, channels_1.closeChannel);
router.get('/localremotebalance', authCheck_1.isAuthenticated, channels_1.getLocalRemoteBalance);
router.get('/listForwards', authCheck_1.isAuthenticated, channels_1.listForwards);
exports.default = router;
