"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authCheck_1 = require("../../utils/authCheck");
const boltz_1 = require("../../controllers/shared/boltz");
const router = express_1.Router();
router.get('/info', authCheck_1.isAuthenticated, boltz_1.getInfo);
router.get('/serviceInfo', authCheck_1.isAuthenticated, boltz_1.getServiceInfo);
router.get('/listSwaps', authCheck_1.isAuthenticated, boltz_1.listSwaps);
router.get('/swapInfo/:swapId', authCheck_1.isAuthenticated, boltz_1.getSwapInfo);
router.post('/createSwap', authCheck_1.isAuthenticated, boltz_1.createSwap);
router.post('/createReverseSwap', authCheck_1.isAuthenticated, boltz_1.createReverseSwap);
router.post('/createChannel', authCheck_1.isAuthenticated, boltz_1.createChannel);
router.post('/deposit', authCheck_1.isAuthenticated, boltz_1.deposit);
exports.default = router;
