"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authCheck_1 = require("../../utils/authCheck");
const loop_1 = require("../../controllers/shared/loop");
const router = express_1.Router();
router.get('/in/terms', authCheck_1.isAuthenticated, loop_1.loopInTerms);
router.get('/in/quote/:amount', authCheck_1.isAuthenticated, loop_1.loopInQuote);
router.get('/in/termsAndQuotes', authCheck_1.isAuthenticated, loop_1.loopInTermsAndQuotes);
router.post('/in', authCheck_1.isAuthenticated, loop_1.loopIn);
router.get('/out/terms', authCheck_1.isAuthenticated, loop_1.loopOutTerms);
router.get('/out/quote/:amount', authCheck_1.isAuthenticated, loop_1.loopOutQuote);
router.get('/out/termsAndQuotes', authCheck_1.isAuthenticated, loop_1.loopOutTermsAndQuotes);
router.post('/out', authCheck_1.isAuthenticated, loop_1.loopOut);
router.get('/swaps', authCheck_1.isAuthenticated, loop_1.swaps);
router.get('/swap/:id', authCheck_1.isAuthenticated, loop_1.swap);
exports.default = router;
