"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authCheck_1 = require("../../utils/authCheck");
const RTLConf_1 = require("../../controllers/shared/RTLConf");
const router = express_1.Router();
router.get('/rtlconfinit', RTLConf_1.getRTLConfigInitial);
router.get('/rtlconf', authCheck_1.isAuthenticated, RTLConf_1.getRTLConfig);
router.post('/', authCheck_1.isAuthenticated, RTLConf_1.updateUISettings);
router.post('/update2FA', authCheck_1.isAuthenticated, RTLConf_1.update2FASettings);
router.get('/config/:nodeType', authCheck_1.isAuthenticated, RTLConf_1.getConfig);
router.get('/file', authCheck_1.isAuthenticated, RTLConf_1.getFile);
router.post('/updateSelNode', RTLConf_1.updateSelectedNode);
router.post('/updateDefaultNode', RTLConf_1.updateDefaultNode);
router.post('/updateServiceSettings', RTLConf_1.updateServiceSettings);
router.post('/updateSSO', RTLConf_1.updateSSO);
router.get('/rates', RTLConf_1.getCurrencyRates);
exports.default = router;
